export const colleges_obj = {
  main : [
    { name: "College of Engineering and Architecture", key: "cea", campus: "main" },
    { name: "College of Teacher Education", key: "cte", campus: "main" },
    { name: "College of Arts and Sciences", key: "cas", campus: "main" },
    { name: "College of Business and Management", key: "cbm", campus: "main" },
    { name: "College of Technology and Allied Sciences", key: "ctas", campus: "main" },
    { name: "College of Advanced Studies", key: "cads", campus: "main" },
    { name: "School of Medicine", key: "med", campus: "main" },
  ],
  balilihan : [
    { name: "College of Technology and Allied Sciences", key: "ctas", campus: "balilihan" },
    { name: "College of Criminal Justice", key: "ccj", campus: "balilihan" },
  ],
  bilar: [
    { name: "College of Agriculture and Natural Sciences", key: "cans", campus: "bilar" },
    { name: "College of Teacher Education", key: "cte", campus: "bilar" },
    { name: "College of Technology and Allied Sciences", key: "ctas", campus: "bilar" },
    { name: "College of Advanced Studies", key: "cads", campus: "bilar" },
  ],
  calape: [
    { name: "College of Teacher Education", key: "cte", campus: "calape" },
    { name: "College of Technology and Allied Sciences", key: "ctas", campus: "calape" },
  ],
  candijay: [
    { name: "College of Fisheries and Marine Sciences", key: "cfms", campus: "candijay" },
    { name: "College of Teacher Education", key: "cte", campus: "candijay" },
    { name: "College of Technology and Allied Sciences", key: "ctas", campus: "candijay" },
    { name: "College of Advanced Studies", key: "cads", campus: "candijay" },
  ],
  clarin: [
    { name: "College of Teacher Education", key: "cte", campus: "clarin" },
    { name: "College of Technology and Allied Sciences", key: "ctas", campus: "clarin" },
  ]
}

export type collegeType = {
  name: string,
  key: string,
  campus: Array<string>
}

export const colleges_list = [
  { name: "College of Engineering and Architecture", key: "cea", campus: ["main"] },
  { name: "College of Teacher Education", key: "cte", campus: ["main","bilar", "calape", "candijay", "clarin"] },
  { name: "College of Arts and Sciences", key: "cas", campus: ["main"] },
  { name: "College of Business and Management", key: "cbm", campus: ["main"] },
  { name: "College of Technology and Allied Sciences", key: "ctas", campus: ["main", "balilihan", "bilar", "calape", "candijay", "clarin"] },
  { name: "College of Advanced Studies", key: "cads", campus: ["main", "bilar", "candijay"] },
  { name: "School of Medicine", key: "med", campus: ["main"] },
  { name: "College of Criminal Justice", key: "ccj", campus: ["balilihan"] },
  { name: "College of Agriculture and Natural Sciences", key: "cans", campus: ["bilar"] },
  { name: "College of Fisheries and Marine Sciences", key: "cfms", campus: ["candijay"] },
]

export const colleges_list_const = [
  "College of Engineering and Architecture",
  "College of Teacher Education",
  "College of Arts and Sciences",
  "College of Business and Management",
  "College of Technology and Allied Sciences",
  "College of Advanced Studies",
  "School of Medicine",
  "College of Criminal Justice",
  "College of Agriculture and Natural Sciences",
  "College of Fisheries and Marine Sciences",
] as const

export type programType = {
  name: string,
  key: string,
  college: string,
  campus: Array<string>,
}

export const program_list = [
  // cea
  { college: "cea", name: "Bachelor of Science in Civil Engineering", key: "bsce", campus: ["main"] },
  { college: "cea", name: "Bachelor of Science in Computer Engineering", key: "bscpe", campus: ["main"] },
  { college: "cea", name: "Bachelor of Science in Electrical Engineering", key: "bsee", campus: ["main"] },
  { college: "cea", name: "Bachelor of Science in Mechanical Engineering", key: "bsme", campus: ["main"] },
  { college: "cea", name: "Bachelor of Science in Architecture", key: "bsarch", campus: ["main"] },
  { college: "cea", name: "Bachelor of Science in Fine Arts major in Industrial Design", key: "bsfa_id", campus: ["main"] },
  // cte
  { college: "cte", name: "Bachelor of Elementary Education", key: "beed", campus: ["main", "calape", "candijay", "clarin"] },
  { college: "cte", name: "Bachelor of Elementary Education major in General Education", key: "beed_gened", campus: ["bilar"] },
  { college: "cte", name: "Bachelor of Secondary Education major in English", key: "bsed_eng", campus: ["main", "bilar", "calape", "candijay"] },
  { college: "cte", name: "Bachelor of Secondary Education major in Filipino", key: "bsed_fil", campus: ["main", "bilar", "candijay"] },
  { college: "cte", name: "Bachelor of Secondary Education major in Science", key: "bsed_sci", campus: ["candijay"] },
  { college: "cte", name: "Bachelor of Secondary Education major in Mathematics", key: "bsed_math", campus: ["main", "bilar", "calape", "candijay", "clarin"] },
  { college: "cte", name: "Bachelor of Secondary Education major in Social Studies", key: "bsed_socstud", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technology and Livelihood Education", key: "btle", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technology and Livelihood Education major in Industrial Technology", key: "btle_it", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technology and Livelihood Education major in Home Economics", key: "btle_he", campus: ["main", "bilar", "clarin"] },
  { college: "cte", name: "Bachelor of Technology and Livelihood Education major in Agri-Fishery Arts", key: "btle_agrifishery", campus: ["bilar"] },
  { college: "cte", name: "Bachelor of Technical Vocational Teacher Education", key: "btvted", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technical Vocational Teacher Education major in Beauty Care and Wellness", key: "btvted_bcw", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technical Vocational Teacher Education major in Automotive Technology", key: "btvted_at", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technical Vocational Teacher Education major in Civil and Construction Technology", key: "btvted_cct", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technical Vocational Teacher Education major in Electrical and Technology", key: "btvted_elect", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technical Vocational Teacher Education major in Food and Services Management", key: "btvted_fsm", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technical Vocational Teacher Education major in Garments and Fashion Design", key: "btvted_gfd", campus: ["main"] },
  { college: "cte", name: "Bachelor of Technical Vocational Teacher Education major in Hotel and Restaurant Services Technology", key: "btvted_hrst", campus: ["main"] },
  // cas
  { college: "cas", name: "Bachelor of Science in Psychology", key: "bspsych", campus: ["main"] },
  // cbm
  { college: "cbm", name: "Bachelor of Science in Entrepreneurship", key: "bsentrep", campus: ["main"] },
  { college: "cbm", name: "Bachelor of Science in Hospitality Management", key: "bshm", campus: ["main"] },
  { college: "cbm", name: "Bachelor of Science in Tourism Management", key: "bstm", campus: ["main"] },
  { college: "cbm", name: "Bachelor of Science in Office Administration", key: "bsoad", campus: ["main"] },
  // ctas
  { college: "ctas", name: "Bachelor of Science in Environmental Science major in Coastal Resource Management", key: "bsenvis_crm", campus: ["clarin"] },
  { college: "ctas", name: "Bachelor of Science in Fisheries", key: "bsfisheries", campus: ["calape"] },
  { college: "ctas", name: "Bachelor of Science in Midwifery", key: "bsmidwifery", campus: ["calape"] },
  { college: "ctas", name: "Bachelor of Science in Entrepreneurship", key: "bsentrep", campus: ["bilar"] },
  { college: "ctas", name: "Bachelor of Science in Hospitality Management", key: "bshm", campus: ["bilar", "candijay", "clarin"] },
  { college: "ctas", name: "Bachelor of Science in Office Administration", key: "bsoad", campus: ["bilar", "candijay"] },
  { college: "ctas", name: "Bachelor of Science in Information Technology", key: "bsit", campus: ["balilihan"] },
  { college: "ctas", name: "Bachelor of Science in Computer Science", key: "bscs", campus: ["balilihan", "bilar", "calape", "candijay", "clarin"] },
  { college: "ctas", name: "Bachelor of Science in Electrical Technology", key: "bselect", campus: ["main", "balilihan"] },
  { college: "ctas", name: "Bachelor of Science in Electronics Technology", key: "bselext", campus: ["main", "balilihan"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Electrical Technology", key: "bsit_elect", campus: ["calape"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Automotive Technology", key: "bsit_auto", campus: ["main", "bilar"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Civil Technology", key: "bsit_civiltech", campus: ["main"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Cosmetology Technology", key: "bsit_cosmetech", campus: ["main"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Drafting Technology", key: "bsit_drafting", campus: ["main"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Food Preparation and Service Management", key: "bsit_foodtech", campus: ["main", "balilihan", "bilar", "calape"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Garments Technology", key: "bsit_garments", campus: ["main", "balilihan"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Heating, Ventilating, Air-Conditioning, and Refrigeration Technology", key: "bsit_hvacr", campus: ["main"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Mechanical Technology", key: "bsit_mechtech", campus: ["main"] },
  { college: "ctas", name: "Bachelor of Science in Industrial Technology major in Wood Technology", key: "bsit_woodtech", campus: ["main"] },
  { college: "ctas", name: "Diploma in Electrical Technology", key: "dip_elect", campus: ["main"] },
  { college: "ctas", name: "Diploma in Electronics Technology", key: "dip_elext", campus: ["main"] },
  { college: "ctas", name: "Diploma in Industrial Technology major in Automotive Technology", key: "dip_auto", campus: ["main"] },
  { college: "ctas", name: "Diploma in Industrial Technology major in Civil Technology", key: "dip_civiltech", campus: ["main"] },
  { college: "ctas", name: "Diploma in Industrial Technology major in Cosmetology Technology", key: "dip_cosmetech", campus: ["main"] },
  { college: "ctas", name: "Diploma in Industrial Technology major in Drafting Technology", key: "dip_drafting", campus: ["main"] },
  { college: "ctas", name: "Diploma in Industrial Technology major in Food Preparation and Service Management", key: "dip_foodtech", campus: ["main"] },
  { college: "ctas", name: "Diploma in Industrial Technology major in Garments Technology", key: "dip_garments", campus: ["main"] },
  { college: "ctas", name: "Diploma in Industrial Technology major in Heating, Ventilating, Air-Conditioning, and Refrigeration Technology", key: "dip_hvacr", campus: ["main"] },
  { college: "ctas", name: "Diploma in Industrial Technology major in Mechanical Technology", key: "dip_mechtech", campus: ["main"] },
  { college: "ctas", name: "Diploma in Industrial Technology major in Wood Technology", key: "dip_woodtech", campus: ["main"] },
  // cads
  { college: "cads", name: "Doctor of Education major in Educational Management", key: "edd_em", campus: ["main", "bilar"] },
  { college: "cads", name: "Doctor of Philosophy major in Technology Management", key: "phd_tm", campus: ["main"] },
  { college: "cads", name: "Doctor of Philosophy major in Community Development", key: "phd_cd", campus: ["bilar"] },
  { college: "cads", name: "Master of Agriculture and Development major in Community Development", key: "mad_cd", campus: ["bilar"] },
  { college: "cads", name: "Master of Agriculture and Development major in Agricultural Development", key: "mad_ad", campus: ["bilar"] },
  { college: "cads", name: "Master of Agriculture and Development major in Agricultural Education", key: "mad_ae", campus: ["bilar"] },
  { college: "cads", name: "Master of Agriculture and Development major in Rural Systems Management", key: "mad_rsm", campus: ["bilar"] },
  { college: "cads", name: "Master in Public Administration major in Personnel Development", key: "mpa_pd", campus: ["bilar"] },
  { college: "cads", name: "Master in Public Administration", key: "mpa", campus: ["main"] },
  { college: "cads", name: "Master of Science in Mathematics", key: "ms_math", campus: ["main"] },
  { college: "cads", name: "Master of Education major in Educational Management", key: "me_em", campus: ["main", "candijay"] },
  { college: "cads", name: "Master of Arts in Teaching Vocational Education major in Automotive Technology", key: "matve_auto", campus: ["main"] },
  { college: "cads", name: "Master of Arts in Teaching Vocational Education major in Civil Technology", key: "matve_civiltech", campus: ["main"] },
  { college: "cads", name: "Master of Arts in Teaching Vocational Education major in Drafting Technology", key: "matve_drafting", campus: ["main"] },
  { college: "cads", name: "Master of Arts in Teaching Vocational Education major in Electrical Technology", key: "matve_elect", campus: ["main"] },
  { college: "cads", name: "Master of Arts in Teaching Vocational Education major in Electronics Technology", key: "matve_elext", campus: ["main"] },
  { college: "cads", name: "Master of Arts in Teaching Vocational Education major in Food Preparation and Service Management", key: "matve_foodtech", campus: ["main"] },
  { college: "cads", name: "Master of Arts in Teaching Vocational Education major in Garments Technology", key: "matve_garments", campus: ["main"] },
  { college: "cads", name: "Master of Arts in Teaching Vocational Education major in Mechanical Technology", key: "matve_mechtech", campus: ["main"] },
  { college: "cads", name: "Master of Science in Industrial Technology major in Automotive Technology", key: "msit_auto", campus: ["main"] },
  { college: "cads", name: "Master of Science in Industrial Technology major in Civil Technology", key: "msit_civiltech", campus: ["main"] },
  { college: "cads", name: "Master of Science in Industrial Technology major in Drafting Technology", key: "msit_drafting", campus: ["main"] },
  { college: "cads", name: "Master of Science in Industrial Technology major in Electrical Technology", key: "msit_elect", campus: ["main"] },
  { college: "cads", name: "Master of Science in Industrial Technology major in Electronics Technology", key: "msit_elext", campus: ["main"] },
  { college: "cads", name: "Master of Science in Industrial Technology major in Food Preparation and Service Management", key: "msit_foodtech", campus: ["main"] },
  { college: "cads", name: "Master of Science in Industrial Technology major in Garments Technology", key: "msit_garments", campus: ["main"] },
  { college: "cads", name: "Master of Science in Industrial Technology major in Mechanical Technology", key: "msit_mechtech", campus: ["main"] },
  // med
  { college: "med", name: "Doctor of Medicine", key: "md", campus: ["main"] },
  // ccj balilihan
  { college: "ccj", name: "Bachelor of Science in Criminology", key: "bscrim", campus: ["balilihan"] },
  // cans bilar
  { college: "cans", name: "Bachelor of Science in Agriculture", key: "bsagri", campus: ["bilar"] },
  { college: "cans", name: "Bachelor of Science in Agricultural and Biosystems Engineering", key: "bsagribioeng", campus: ["bilar"] },
  { college: "cans", name: "Bachelor of Science in Environmental Science", key: "bsenvs", campus: ["bilar"] },
  { college: "cans", name: "Bachelor of Science in Forestry", key: "bsforestry", campus: ["bilar"] },
  // cfms
  { college: "cfms", name: "Bachelor of Science in Fisheries", key: "bsfisheries", campus: ["candijay"] },
  { college: "cfms", name: "Bachelor of Science in Marine Biology", key: "bsmarinebio", campus: ["candijay"] },
  { college: "cfms", name: "Bachelor of Science in Environmental Science major in Coastal Resource Management", key: "bsenvis_crm", campus: ["candijay"] },
]


export const program_list_const = [
  // cea
  "Bachelor of Science in Civil Engineering",
  "Bachelor of Science in Computer Engineering",
  "Bachelor of Science in Electrical Engineering",
  "Bachelor of Science in Mechanical Engineering",
  "Bachelor of Science in Architecture",
  "Bachelor of Science in Fine Arts major in Industrial Design",
  // cte
  "Bachelor of Elementary Education",
  "Bachelor of Elementary Education major in General Education",
  "Bachelor of Secondary Education major in English",
  "Bachelor of Secondary Education major in Filipino",
  "Bachelor of Secondary Education major in Science",
  "Bachelor of Secondary Education major in Mathematics",
  "Bachelor of Secondary Education major in Social Studies",
  "Bachelor of Technology and Livelihood Education",
  "Bachelor of Technology and Livelihood Education major in Industrial Technology",
  "Bachelor of Technology and Livelihood Education major in Home Economics",
  "Bachelor of Technology and Livelihood Education major in Agri-Fishery Arts",
  "Bachelor of Technical Vocational Teacher Education",
  "Bachelor of Technical Vocational Teacher Education major in Beauty Care and Wellness",
  "Bachelor of Technical Vocational Teacher Education major in Automotive Technology",
  "Bachelor of Technical Vocational Teacher Education major in Civil and Construction Technology",
  "Bachelor of Technical Vocational Teacher Education major in Electrical and Technology",
  "Bachelor of Technical Vocational Teacher Education major in Food and Services Management",
  "Bachelor of Technical Vocational Teacher Education major in Garments and Fashion Design",
  "Bachelor of Technical Vocational Teacher Education major in Hotel and Restaurant Services Technology",
  // cas
  "Bachelor of Science in Psychology",
  // cbm
  "Bachelor of Science in Entrepreneurship",
  "Bachelor of Science in Hospitality Management",
  "Bachelor of Science in Tourism Management",
  "Bachelor of Science in Office Administration",
  // ctas
  //  "Bachelor of Science in Environmental Science major in Coastal Resource Management",
  //  "Bachelor of Science in Fisheries",
   "Bachelor of Science in Midwifery",
  //  "Bachelor of Science in Entrepreneurship",
  //  "Bachelor of Science in Hospitality Management",
  //  "Bachelor of Science in Office Administration",
   "Bachelor of Science in Information Technology",
   "Bachelor of Science in Computer Science",
   "Bachelor of Science in Electrical Technology",
   "Bachelor of Science in Electronics Technology",
   "Bachelor of Science in Industrial Technology major in Electrical Technology",
   "Bachelor of Science in Industrial Technology major in Automotive Technology",
   "Bachelor of Science in Industrial Technology major in Civil Technology",
   "Bachelor of Science in Industrial Technology major in Cosmetology Technology",
   "Bachelor of Science in Industrial Technology major in Drafting Technology",
   "Bachelor of Science in Industrial Technology major in Food Preparation and Service Management",
   "Bachelor of Science in Industrial Technology major in Garments Technology",
   "Bachelor of Science in Industrial Technology major in Heating, Ventilating, Air-Conditioning, and Refrigeration Technology",
   "Bachelor of Science in Industrial Technology major in Mechanical Technology",
   "Bachelor of Science in Industrial Technology major in Wood Technology",
   "Diploma in Electrical Technology",
   "Diploma in Electronics Technology",
   "Diploma in Industrial Technology major in Automotive Technology",
   "Diploma in Industrial Technology major in Civil Technology",
   "Diploma in Industrial Technology major in Cosmetology Technology",
   "Diploma in Industrial Technology major in Drafting Technology",
   "Diploma in Industrial Technology major in Food Preparation and Service Management",
   "Diploma in Industrial Technology major in Garments Technology",
   "Diploma in Industrial Technology major in Heating, Ventilating, Air-Conditioning, and Refrigeration Technology",
   "Diploma in Industrial Technology major in Mechanical Technology",
   "Diploma in Industrial Technology major in Wood Technology",
  // cads
   "Doctor of Education major in Educational Management",
   "Doctor of Philosophy major in Technology Management",
   "Doctor of Philosophy major in Community Development",
   "Master of Agriculture and Development major in Community Development",
   "Master of Agriculture and Development major in Agricultural Development",
   "Master of Agriculture and Development major in Agricultural Education",
   "Master of Agriculture and Development major in Rural Systems Management",
   "Master in Public Administration major in Personnel Development",
   "Master in Public Administration",
   "Master of Science in Mathematics",
   "Master of Education major in Educational Management",
   "Master of Arts in Teaching Vocational Education major in Automotive Technology",
   "Master of Arts in Teaching Vocational Education major in Civil Technology",
   "Master of Arts in Teaching Vocational Education major in Drafting Technology",
   "Master of Arts in Teaching Vocational Education major in Electrical Technology",
   "Master of Arts in Teaching Vocational Education major in Electronics Technology",
   "Master of Arts in Teaching Vocational Education major in Food Preparation and Service Management",
   "Master of Arts in Teaching Vocational Education major in Garments Technology",
   "Master of Arts in Teaching Vocational Education major in Mechanical Technology",
   "Master of Science in Industrial Technology major in Automotive Technology",
   "Master of Science in Industrial Technology major in Civil Technology",
   "Master of Science in Industrial Technology major in Drafting Technology",
   "Master of Science in Industrial Technology major in Electrical Technology",
   "Master of Science in Industrial Technology major in Electronics Technology",
   "Master of Science in Industrial Technology major in Food Preparation and Service Management",
   "Master of Science in Industrial Technology major in Garments Technology",
   "Master of Science in Industrial Technology major in Mechanical Technology",
  // med
  "Doctor of Medicine",
  // ccj balilihan
  "Bachelor of Science in Criminology",
  // cans bilar
   "Bachelor of Science in Agriculture",
   "Bachelor of Science in Agricultural and Biosystems Engineering",
   "Bachelor of Science in Environmental Science",
   "Bachelor of Science in Forestry",
  // cfms
   "Bachelor of Science in Fisheries",
   "Bachelor of Science in Marine Biology",
   "Bachelor of Science in Environmental Science major in Coastal Resource Management",
] as const